### PR TITLE
Cherry-pick: Fix broken links (#411)

### PR DESCRIPTION
**Pull request by epons-stratio**

### CODE REVIEW

**Comment by stratiocommit** [comment]
Because the pull request author hasn't admin or write permission, the build will use the Jenkinsfile from the target branch on the origin repository.

**Comment by stratiocommit** [comment]
Because the pull request author hasn't admin or write permission, the build will use the Jenkinsfile from the target branch on the origin repository.

**Review by stg-0 — APPROVED** [review]
lgtm

**Comment by stratiocommit** [comment]
Because the pull request author hasn't admin or write permission, the build will use the Jenkinsfile from the target branch on the origin repository.

**Pull request merged**
