### PR TITLE
[Azure] add validation of registry types

### PR DESCRIPTION
**Pull request by esierra-stratio**
- Only one defined registry
```yaml
    docker_registries:
        - url: eosregistry.azurecr.io/keos
          auth_required: false
          type: acr
          keos_registry: true
```
Output:
```bash
Cluster descriptor is valid
```

- Multiple defined registries with same type
```yaml
    docker_registries:
        - url: eosregistry.azurecr.io/keos
          auth_required: false
          type: acr
          keos_registry: true
        - url: aeosregistry.azurecr.io/keos
          auth_required: false
          type: acr
```
Output
```bash
Cluster descriptor is valid
```

- Multiple defined registries with different type
```yaml
    docker_registries:
        - url: eosregistry.azurecr.io/keos
          auth_required: false
          type: acr
          keos_registry: true
        - url: aeosregistry.azurecr.io/keos
          auth_required: false
          type: generic
```
Output
```bash
ERROR: failed to validate cluster: spec.docker_registries[1]: Invalid value: "type": inconsistent registry types, the types among the defined registries must be the same
```

### CODE REVIEW

**Comment by dandres-stratio** [comment]
:pray:

**Comment by dandres-stratio** [comment]
:pray:

**Comment by dandres-stratio** [comment]
:pray:

**Comment by dandres-stratio** [comment]
:pray:

**Comment by dandres-stratio** [comment]
:pray:

**Comment by dandres-stratio** [comment]
:pray:

**Comment by dandres-stratio** [comment]
:pray:

**Review by iamjanr — APPROVED** [review]
LGTM

**Pull request merged**
