### PR TITLE
[CLOUD-127] Refinar maxUnhealthy de MachineHealthCheck

### PR DESCRIPTION
**Pull request by esierra-stratio**
It applies only to MachineDeployment or MachineSet

### Control plane

34% of unhealthy machines corresponds the maximum allowable number of failures, with Q=(N/2)+1, where N=3

### Workers

50% of unhealthy machines is considered the threshold to automatically handle a cluster recovery beyond that point a human interaction is required.

### CODE REVIEW

**Review by dandres-stratio — APPROVED** [review]
LGTM

Tested in all cloud providers.
AKS is excluded from this as it doesn't support Machines

**Comment by dandres-stratio** [comment]
:pray:

**Comment by dandres-stratio** [comment]
:pray:

**Comment by esierra-stratio** [comment]
:pray:

**Pull request merged**
