### PR TITLE
[branch-0.3] EN doc added and ES fixes

### PR DESCRIPTION
**Pull request by tperez-stratio**

### CODE REVIEW

**Comment by stratiocommit** [comment]
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
ES - modules/ROOT/pages/aws-image-builder.adoc
ES - modules/ROOT/pages/azure-image-builder.adoc
ES - modules/ROOT/pages/gcp-image-builder.adoc
ES - modules/ROOT/pages/operations.adoc

**Comment by stratiocommit** [comment]
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
ES - modules/ROOT/pages/aws-image-builder.adoc
ES - modules/ROOT/pages/azure-image-builder.adoc
ES - modules/ROOT/pages/gcp-image-builder.adoc
ES - modules/ROOT/pages/operations.adoc

**Comment by stratiocommit** [comment]
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
ES - modules/ROOT/pages/aws-image-builder.adoc
ES - modules/ROOT/pages/azure-image-builder.adoc
ES - modules/ROOT/pages/gcp-image-builder.adoc
ES - modules/ROOT/pages/operations.adoc

**Review by iamjanr — APPROVED** [review]
LGTM

**Pull request merged**
