### PR TITLE
[CLOUD-169] [AWS] Refinar integracion de aws-loadbalancer-controller

### PR DESCRIPTION
**Pull request by esierra-stratio**

### CODE REVIEW

**Comment by stratiocommit** [comment]
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/installation.adoc

**Comment by stratiocommit** [comment]
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/installation.adoc

**Comment by dandres-stratio** [comment]
:pray:

**Comment by stratiocommit** [comment]
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/installation.adoc

**Comment by stratiocommit** [comment]
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/installation.adoc

**Comment by stratiocommit** [comment]
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/installation.adoc

**Comment by stratiocommit** [comment]
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/installation.adoc

**Comment by stratiocommit** [comment]
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/installation.adoc

**Comment by stratiocommit** [comment]
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/installation.adoc

**Review by dandres-stratio — APPROVED** [review]
LGTM

**Comment by stratiocommit** [comment]
This PR has modified files that have not been added for all versions. Please add them including the text [to be translated] so that the reviewer can easily upload or modify the translated versions. Missing folder/files:
EN - modules/ROOT/pages/installation.adoc

**Pull request merged**
